name: Claude Issue Triage
description: Run Claude Code for issue triage in GitHub Actions
on:
  issues:
    types: [opened]

jobs:
  triage-issue:
    runs-on: [self-hosted, ubuntu-latest]
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write

    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          # Specify the current repository and any submodule repositories
          owner: ${{ github.repository_owner }}
          repositories: |
            ${{ github.event.repository.name }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0

      - name: Run Claude Code for Issue Triage
        uses: anthropics/claude-code-action@main
        with:
          prompt: "/label-issue REPO: ${{ github.repository }} ISSUE_NUMBER${{ github.event.issue.number }}"
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ steps.generate-token.outputs.token }}
